# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: JULIO KENJI UEDA
# Description of the Site
description: Desenvolvedor de Software, Cientista da Computação e Gamer
# URL of Image of the Site
site-image: /assets/images/meta.png
# Keywords of the Site
site-keywords: Site, Template, Theme
# URL for the Image of custom Favicon
favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: /assets/images/heroimage.jpg
#https://images.pexels.com/photos/220444/pexels-photo-220444.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: contato@akumaex.com
facebook_username: AkumaEX
twitter_username: AkumaEX
instagram_username: akumaex
linkedin_username: akumaex
github_username: AkumaEX
hackerrank_username: akumaex
youtube_channel_id: UCOlpfi8pX5AGBfCOi7mN5SQ
reddit_username: AkumaEX
steam_username: akumaex
twitch_username: akumaex
spotify_username: akumaex

# Google Analytics
google-analytics: G-RTTQ8K2XR2

# Disqus
disqus-shortname: AkumaEX

# Name of the Author
author-name: JULIO KENJI UEDA
# URL for the Image of the Author
author-image: /assets/images/profile.png
# 60 Words About the Author
author-about: Brasileiro, Paulistano nascido em 1980, cursou todo o Ensino Fundamental e Médio em escola pública. Em 1998 foi trabalhar no Japão e retornou ao Brasil 16 anos depois, para ingresssar no curso de Bacharelado em Ciência da Computação da USP. Hoje, já formado, pretende seguir carreira como Desenvolvedor de Software. Durante toda a vida será Gamer.
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://akumaex.com

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
